// <auto-generated />
using System;
using JawsOfDeath.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JawsOfDeath.Backend.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260811112816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("JawsOfDeath.Backend.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("JawsOfDeath.Backend.Models.ScoreEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeathCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimeSurvived")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeToFirstOrb")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeToKillBoss")
                        .HasColumnType("REAL");

                    b.Property<int>("ZombiesKilled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("ScoreEntries");
                });

            modelBuilder.Entity("JawsOfDeath.Backend.Models.ScoreEntry", b =>
                {
                    b.HasOne("JawsOfDeath.Backend.Models.Player", "Player")
                        .WithMany("ScoreEntries")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("JawsOfDeath.Backend.Models.Player", b =>
                {
                    b.Navigation("ScoreEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
